# Generated by Django 3.1.1 on 2020-09-18 07:54

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import filer.fields.image
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filer', '0012_file_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=django.utils.timezone.now, null=True, unique=True, validators=[django.core.validators.MinValueValidator(2003), main.models.max_value_current_year], verbose_name='Year')),
                ('colourback', colorfield.fields.ColorField(default='rgb(73, 109, 137)', max_length=18, verbose_name='colourback')),
                ('colourtext', colorfield.fields.ColorField(default='#FFF00C', max_length=18, verbose_name='colourtext')),
                ('yeardesc', models.TextField(blank=True, null=True, verbose_name='About the year')),
                ('shashti', models.DateField(blank=True, null=True, verbose_name='Date of Shashti Puja')),
                ('saptami', models.DateField(blank=True, null=True, verbose_name='Date of Saptami Puja')),
                ('ashtami', models.DateField(blank=True, null=True, verbose_name='Date of Ashtami Puja')),
                ('sandhi', models.DateField(blank=True, null=True, verbose_name='Date of Sandhi Puja')),
                ('navami', models.DateField(blank=True, null=True, verbose_name='Date of Navami Puja')),
                ('dashami', models.DateField(blank=True, null=True, verbose_name='Date of Dashami Puja')),
                ('shashtit', models.TimeField(blank=True, null=True, verbose_name='Start Time of Shashti Puja')),
                ('shashtite', models.TimeField(blank=True, null=True, verbose_name='End Time of Shashti Puja')),
                ('saptamit', models.TimeField(blank=True, null=True, verbose_name='Start Time of Saptami Puja')),
                ('saptamite', models.TimeField(blank=True, null=True, verbose_name='End Time of Saptami Puja')),
                ('ashtamit', models.TimeField(blank=True, null=True, verbose_name='Start Time of Ashtami Puja')),
                ('ashtamite', models.TimeField(blank=True, null=True, verbose_name='End Time of Ashtami Puja')),
                ('sandhit', models.TimeField(blank=True, null=True, verbose_name='Start Time of Sandhi Puja')),
                ('sandhite', models.TimeField(blank=True, null=True, verbose_name='End Time of Sandhi Puja')),
                ('navamit', models.TimeField(blank=True, null=True, verbose_name='Start Time of Navami Puja')),
                ('navamite', models.TimeField(blank=True, null=True, verbose_name='End Time of Navami Puja')),
                ('dashamit', models.TimeField(blank=True, null=True, verbose_name='Start Time of Dashami Puja')),
                ('dashamite', models.TimeField(blank=True, null=True, verbose_name='End Time of Dashami Puja')),
                ('dashamite1', models.DateTimeField(blank=True, null=True, verbose_name='End1 Time of Dashami Puja')),
                ('pujadatetime', filer.fields.file.FilerFileField(blank=True, help_text='This must be a file a pdf, or an image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puja_schedule', to='filer.file', verbose_name='Puja schedule file')),
                ('yearpic', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_back_picture', to=settings.FILER_IMAGE_MODEL, verbose_name='Year Background Image')),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('S', 'Maha Shashti'), ('SA', 'Maha Saptami'), ('A', 'Maha Ashtami'), ('SAN', 'Sandhi Puja'), ('N', 'Maha Navami'), ('D', 'Maha Dashami')], max_length=50, null=True, verbose_name='Day of Uploading')),
                ('streamingplatform', models.CharField(blank=True, choices=[('F', 'Facebook'), ('Y', 'YouTube')], max_length=10, null=True, validators=[main.models.validate_platform], verbose_name='Streaming Platform')),
                ('streamingvideoheader', models.CharField(blank=True, max_length=600, null=True, verbose_name='Live Streaming Video Header')),
                ('streamingvideolink', models.URLField(blank=True, null=True, verbose_name='Live Video Link')),
                ('videoid', models.CharField(blank=True, max_length=500, null=True, verbose_name='Facebook/YouTube Video ID')),
                ('usernamefb', models.CharField(blank=True, max_length=500, null=True, verbose_name='Facebook User ID')),
                ('embeedlink', models.URLField(blank=True, null=True, verbose_name='Embeed Link of Posts or Video')),
                ('streamingvideodescription', models.TextField(blank=True, help_text='This is optional', null=True, verbose_name='Streaming Video Short Description')),
                ('yearmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.year', verbose_name='Year')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
