# Generated by Django 3.2.4 on 2021-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='test',
            field=models.BooleanField(default=False, help_text='Check this only when you are testing the webhook', verbose_name='Test'),
        ),
    ]
