# Generated by Django 3.1.1 on 2020-09-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='dashamite1',
        ),
    ]
