# Generated by Django 3.1.1 on 2020-10-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201016_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='maacomevid',
            field=models.BooleanField(default=True, help_text='Check this checkbox if there will be any video of the Maa coming to home', verbose_name='Will there be any video for the Maa Durga coming to home'),
        ),
    ]
