# Generated by Django 3.1.1 on 2020-09-18 08:33

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('main', '0002_remove_year_dashamite1'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='maadurgaphoto',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maa_durga_photo', to='filer.file', verbose_name='Corresponding year Maa Durga Photo'),
        ),
    ]
