# Generated by Django 3.2.4 on 2021-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videos_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='streamingvideolink',
            field=models.URLField(default=None, verbose_name='Live Video Link'),
            preserve_default=False,
        ),
    ]
