# Generated by Django 3.1.1 on 2020-10-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201016_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='day',
            field=models.CharField(blank=True, choices=[('E', 'Ekum'), ('DI', 'Dvitia'), ('T', 'Tritiya'), ('C', 'Maha Chathurti'), ('P', 'Maha Panchami'), ('S', 'Maha Shashti'), ('SA', 'Maha Saptami'), ('A', 'Maha Ashtami'), ('SAN', 'Sandhi Puja'), ('N', 'Maha Navami'), ('D', 'Maha Dashami')], default='S', max_length=50, null=True, verbose_name='Day of Uploading'),
        ),
    ]
