# Generated by Django 3.1.1 on 2020-09-18 08:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_year_maadurgaphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='live',
            field=models.BooleanField(default=True, verbose_name='If the video is live or not'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='streamingplatform',
            field=models.CharField(blank=True, choices=[('F', 'Facebook'), ('Y', 'YouTube')], default='F', max_length=10, null=True, validators=[main.models.validate_platform], verbose_name='Streaming Platform'),
        ),
    ]
