# Generated by Django 3.2.7 on 2021-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_year_colourback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='streamingplatform',
            field=models.CharField(blank=True, choices=[('F', 'Facebook'), ('Y', 'YouTube')], default='F', max_length=10, null=True, verbose_name='Streaming Platform'),
        ),
    ]
