# Generated by Django 3.1.1 on 2020-09-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200918_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='live',
            field=models.BooleanField(default=True, help_text='Check this only if the video is live', verbose_name='Live Video'),
        ),
    ]
