# Generated by Django 3.1.1 on 2020-09-18 11:42

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200918_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='yearmodel',
            field=models.ForeignKey(default=main.models.get_default_year, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.year', verbose_name='Year'),
        ),
    ]
