# Generated by Django 3.1.1 on 2020-09-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200918_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='pujadatetime',
        ),
    ]
