# Generated by Django 3.1.1 on 2020-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_year_mahabhog'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='mahabhogdttime',
            field=models.DateTimeField(blank=True, help_text='Fill this only when "Maha Bhog checkbox" is clicked.', null=True, verbose_name='Maha Bhog Date and Time'),
        ),
    ]
