# Generated by Django 3.1.1 on 2020-09-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_year_mahabhogdttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='mahabhog',
            field=models.BooleanField(default=False, help_text='Click only when Maha Bhog is organised.', verbose_name='Maha Bhog is there ?'),
        ),
    ]
